server:
  port: 7877

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/security
    username: root
    password: samit@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: SECURITY-SERVICE-DB

jwt:
  secretKey: jjhfjkhfjkhadjkhdjkvhdjkvhjkavhjkhjdvk


